# Generated by Django 5.1.4 on 2025-01-03 14:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='samples/default_post_w4tzg1', max_length=255, verbose_name='image'),
        ),
    ]
