# Generated by Django 5.1.4 on 2025-01-04 14:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_post_rgq6aq', max_length=255, verbose_name='image'),
        ),
    ]
