# Generated by Django 5.1.4 on 2025-01-03 13:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/du7daaai2/image/upload/default_profile_fhledc', max_length=255, verbose_name='image'),
        ),
    ]
