# Generated by Django 5.1.4 on 2025-01-03 14:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_profile_profile_image_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='samples/default_profile_fhledc', max_length=255, verbose_name='image'),
        ),
    ]
